"""add columns to table

Revision ID: 74328ba9fb12
Revises: 654ea22073b8
Create Date: 2024-07-13 22:13:28.830537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74328ba9fb12'
down_revision = '654ea22073b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
